<?php
        $Template_Langs = array(
                'es' => array(
                        'Home' => 'Inicio',
                        'About' => 'Sobre mí',
                        'Services' => 'Servicios',
                        'Home_a' => '/',
                        'About_a' => '/#sobremi',
                        'Services_a' => 'servicios',
                        'LogoText1' => 'Diseño, maquetación',
                        'LogoText2' => ' y desarrollo web',
                        'Contact' => 'Contáctame',
                        'LangSelected' => 'ES',
                        'indanielweb' => 'indanielweb.es',
                        'Contact_Form' => 'CONTACTO',
                        '404_body' => '404_body_es',
                        'EmailSent_body' => 'EmailSent_body_es',
                        'Contact_body' => 'Contact_body_es',
                        'Contact_Name' => '¿Cual es tu nombre?',
                        'Contact_Email' => '¿Cual es tu correo electrónico?',
                        'Contact_Repeat_Email' => 'Repite tu correo',
                        'Contact_Message' => '¿Como te puedo ayudar?',
                        'Contact_No_Name' => 'Debe introducir el nombre',
                        'Contact_No_Email' => 'Debe introducir el correo',
                        'Contact_No_Valid_Email' => 'El correo electrónico no es válido',
                        'Contact_No_Equal_Email' => 'Los correos no son iguales',
                        'footer_terms' => 'terminos y condiciones de uso - copy right 2017',
                        'footer_terms_a' => 'terminosycondiciones',
                ),
                'en' => array(
                        'Home' => 'Home',
                        'About' => 'About me',
                        'Services' => 'Services',
                        'Home_a' => '/',
                        'About_a' => '/#aboutme',
                        'Services_a' => 'services',
                        'LogoText1' => 'Web design, layout',
                        'LogoText2' => ' and development',
                        'Contact' => 'Contact me',
                        'LangSelected' => 'EN',
                        'indanielweb' => 'indanielweb.com',
                        'Contact_Form' => 'CONTACT',
                        '404_body' => '404_body_en',
                        'EmailSent_body' => 'EmailSent_body_en',
                        'Contact_body' => 'Contact_body_en',
                        'Contact_Name' => "What's your name?",
                        'Contact_Email' => "What's your email?",
                        'Contact_Repeat_Email' => 'Repeat your email',
                        'Contact_Message' => 'How can I help you?',
                        'Contact_No_Name' => 'You have to type the name',
                        'Contact_No_Email' => 'You have to type the email',
                        'Contact_No_Valid_Email' => 'The email is not correct',
                        'Contact_No_Equal_Email' => 'The emails are not equal',
                        'footer_terms' => 'Terms and conditions - copy right 2017',
                        'footer_terms_a' => 'termsandconditions',
                ),
        );

        $Template_Langs = $Template_Langs[$lang];

        $Absolute_Path = 'http://'.DOMAIN;
